services:

  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH}/minio/data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - fabric

networks:
  fabric:
    external: true