services:

  cadvisor:
    container_name: monitoring_cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    privileged: true
    ports:
      - "8084:8080"
    networks:
      - monitoring-net
  
  prometheus:
    container_name: monitoring_prometheus
    image: prom/prometheus:latest
    volumes: 
      - "${DATA_PATH}/monitoring/prometheus:/etc/prometheus"
    ports:
      - "8085:9090"
    privileged: true
    depends_on:
      - cadvisor
    networks:
      - monitoring-net
  
  grafana:
    container_name: monitoring_grafana
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_SIGNOUT_MENU=true
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - DS_PROMETHEUS=prometheus
    volumes: 
      - "${DATA_PATH}/monitoring/grafana/data:/var/lib/grafana"
      - "${DATA_PATH}/monitoring/grafana/provisioning:/etc/grafana/provisioning"
    user: '0'
    ports:
      - "8086:3000"
    privileged: true
    depends_on:
      - cadvisor
    networks:
      - monitoring-net

networks:
  monitoring-net: